version: '3.8'

services:
  backend:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "True"
    volumes:
      - ./backend:/app
    command: ["python", "app.py"]

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["npm", "start"] 